apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.serviceAccount.name }}
  annotations:
    iam.gke.io/gcp-service-account: {{ index .Values.backend.serviceAccount.annotations "iam.gke.io/gcp-service-account" }}
