apiVersion: v1
kind: Service
metadata:
  name: quick-notes-backend
spec:
  type: ClusterIP
  selector:
    app: quick-notes-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  
