apiVersion: v1
kind: Service
metadata:
  name: quick-notes-frontend
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: quick-notes-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      name: http
  loadBalancerIP: {{ .Values.frontend.service.loadBalancerIP }}