apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-notes-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quick-notes-frontend
  template:
    metadata:
      labels:
        app: quick-notes-frontend
        {{- with .Values.frontend.podLabels }}
        {{- toYaml . | nindent 6 }}
        {{- end }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
