apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_HOST: "{{ .Values.mysql.secret.DB_HOST }}"
  DB_PORT: "{{ .Values.mysql.secret.DB_PORT }}"
  DB_NAME: "{{ .Values.mysql.secret.DB_NAME }}"
  DB_USER: "{{ .Values.mysql.secret.DB_USER }}"
  DB_PASSWORD: "{{ .Values.mysql.secret.DB_PASSWORD }}"
  MYSQL_ROOT_PASSWORD: "{{ .Values.mysql.secret.MYSQL_ROOT_PASSWORD }}"


 