apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mysql-init
          image: mysql:8.0
          command:
            - sh
            - -c
            - |
              echo "Waiting for MySQL..."
              until mysqladmin ping -h quick-notes-mysql -u root -p"$MYSQL_ROOT_PASSWORD" --silent; do
                echo "MySQL not ready, waiting..."
                sleep 3
              done

              echo "Creating user, database, and schema..."
              mysql -h quick-notes-mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<EOF
              CREATE DATABASE IF NOT EXISTS notes;
              CREATE USER IF NOT EXISTS 'customuser'@'%' IDENTIFIED BY 'custompass';
              GRANT ALL PRIVILEGES ON notes.* TO 'customuser'@'%';
              FLUSH PRIVILEGES;

              USE notes; 
              CREATE TABLE IF NOT EXISTS notes (
                id INT AUTO_INCREMENT PRIMARY KEY,
                title VARCHAR(255) NOT NULL,
                content TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
              );
              EOF

          envFrom:
            - secretRef:
                name: mysql-secret
