apiVersion: v1
kind: Service
metadata:
  name: quick-notes-mysql
  labels:
    app: quick-notes-mysql
spec:
  type: ClusterIP
  selector:
    app: quick-notes-mysql  
  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}

