version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
    container_name: quick-notes-backend
    depends_on:
      - mysql
    env_file:
      - .env.backend.local
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://localhost:5000/api
    container_name: quick-notes-frontend
    depends_on:
      - backend
    env_file:
      - .env.frontend.local
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

volumes:
  mysql-data: 
