name: Helm Deploy App

on:
  push:
    branches:
      - infra-dev
  workflow_dispatch:
  workflow_run:
    workflows: ["Terraform apply infra"]
    types:
      - completed

jobs:
  helm:
    name: Helm Deploy
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Auth GCP
        run: |
          echo '${{ secrets.GCP_SA_KEY_DEV }}' > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud config set project valiant-realm-458909-q7
        env:
          CLOUDSDK_CORE_DISABLE_PROMPTS: '1'

      - name: Get GKE Credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: quick-notes-dev-gke-cluster
          location: me-west1
          project_id: valiant-realm-458909-q7


      - name: Set up Terraform (to get outputs)
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: infra/dev
        run: terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json

      - name: Extract Terraform Outputs
        working-directory: infra/dev
        id: extract
        run: |
          echo "frontend_lb_ip=$(terraform output -raw frontend_lb_ip)" >> $GITHUB_ENV
          echo "repo_url=$(terraform output -raw repo_url)" >> $GITHUB_ENV
          echo "ksa_name=$(terraform output -raw ksa_name)" >> $GITHUB_ENV
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Install Helm Diff Plugin
        run: helm plugin install https://github.com/databus23/helm-diff || true

      - name: Helm Diff (preview changes)
        working-directory: infra/helm
        run: |
          helm diff upgrade --allow-unreleased quick-notes quick-notes \
            --namespace quick-notes-dev \
            --values quick-notes/values.yaml \
            --set backend.ksa_name="$ksa_name" \
            --set frontend.service.loadBalancerIP="$frontend_lb_ip" \
            --set backend.image.repository="$repo_url/quick-notes-backend" \
            --set frontend.image.repository="$repo_url/quick-notes-frontend"
          
      - name: Helm Deploy
        working-directory: infra/helm
        run: |
          helm upgrade quick-notes quick-notes \
            --install \
            --create-namespace \
            --namespace quick-notes-dev \
            --values quick-notes/values.yaml \
            --debug \
            --set backend.ksa_name="$ksa_name" \
            --set frontend.service.loadBalancerIP="$frontend_lb_ip" \
            --set backend.image.repository="$repo_url/quick-notes-backend" \
            --set frontend.image.repository="$repo_url/quick-notes-frontend"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json



          
    