name: Terraform apply infra

on:
  push:
    branches:
      - infra-dev
      - infra-prod
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_environment: ${{ github.ref_name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Set GCP Project and Auth
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/infra-prod" ]]; then
            echo '${{ secrets.GCP_SA_KEY_PROD }}' > /tmp/gcp-key.json
            echo "PROJECT_ID=quick-notes-prod-458910" >> $GITHUB_ENV
          else
            echo '${{ secrets.GCP_SA_KEY_DEV }}' > /tmp/gcp-key.json
            echo "PROJECT_ID=valiant-realm-458909-q7" >> $GITHUB_ENV
          fi

          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud config set project "$PROJECT_ID"

      - name: Terraform Init + Apply
        working-directory: infra/${{ github.ref_name }}
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Extract env suffix (dev/prod)
        run: |
          echo "ENV_SUFFIX=${GITHUB_REF_NAME#infra-}" >> $GITHUB_ENV


      - name: Trigger Helm Deploy
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: deploy-helm
          client-payload: '{"env": "${{ env.ENV_SUFFIX }}", "tag": "latest"}'